package com.pennywiseai.tracker.ui.icons

import com.pennywiseai.tracker.R

/**
 * One entry in the category-icon picker.
 *
 * [iconName] is a literal, not derived from a `Context` via
 * `Resources.getResourceEntryName` (that's what Cashiro does, and it forces a
 * `Context` through the whole catalog, making it untestable on the JVM). The pair
 * ([iconName], [resourceId]) is the invariant [IconCatalogTest] checks: the name is
 * what gets persisted (see `IconResolutionUtils`), the id is what gets rendered now.
 */
data class IconItem(
    val name: String,        // human label, shown under the icon -- "Pizza"
    val category: String,    // picker group key -- "Food". Stable English key; mapped
                              // to a string resource at render time, not here.
    val iconName: String,    // stable resource name -- "type_food_pizza"
    val resourceId: Int,     // R.drawable.type_food_pizza
    /**
     * Extra search terms for this icon. Cashiro listed a handful of icons twice
     * under two labels ("Purse"/"Wallet", "Headphone"/"Music") to make both words
     * findable. Two tiles of the same picture read as a bug in a grid, so we keep
     * one tile and carry the second word here instead — the icon stays findable
     * under either term without appearing twice.
     *
     * Search must match this as well as [name] and [category].
     */
    val aliases: List<String> = emptyList()
)

/**
 * The category-icon library, ported from Cashiro's `getAllIcons`
 * (`IconSelector.kt`, ~lines 284-1147). No `Context` needed: [all] is a plain list
 * built once and cached.
 */
object IconCatalog {

    val all: List<IconItem> by lazy { buildCatalog() }

    /** Universal fallback when a stored [IconItem.iconName] no longer resolves. */
    val default: IconItem
        get() = all.first { it.iconName == "type_finance_money_bag" }

    private fun buildCatalog(): List<IconItem> {
        val icons = mutableListOf<IconItem>()

        fun addIcon(
            name: String,
            category: String,
            iconName: String,
            resourceId: Int,
            vararg aliases: String
        ) {
            icons.add(IconItem(name, category, iconName, resourceId, aliases.toList()))
        }

        // Animals
        addIcon("Bear", "Animals", "type_animal_bear", R.drawable.type_animal_bear)
        addIcon("Bird", "Animals", "type_animal_bird", R.drawable.type_animal_bird)
        addIcon("Cat", "Animals", "type_animal_cat_face", R.drawable.type_animal_cat_face)
        addIcon("Dog", "Animals", "type_animal_dog_face", R.drawable.type_animal_dog_face)
        addIcon("Fox", "Animals", "type_animal_fox", R.drawable.type_animal_fox)
        addIcon("Lion", "Animals", "type_animal_lion", R.drawable.type_animal_lion)
        addIcon("Panda", "Animals", "type_animal_panda", R.drawable.type_animal_panda)
        addIcon("Tiger", "Animals", "type_animal_tiger_face", R.drawable.type_animal_tiger_face)
        addIcon("Chicken", "Animals", "type_animal_chicken", R.drawable.type_animal_chicken)
        addIcon("Cow", "Animals", "type_animal_cow_face", R.drawable.type_animal_cow_face)
        addIcon("Dove", "Animals", "type_animal_dove", R.drawable.type_animal_dove)
        addIcon("Frog", "Animals", "type_animal_frog", R.drawable.type_animal_frog)
        addIcon("Goblin", "Animals", "type_animal_goblin", R.drawable.type_animal_goblin)
        addIcon("Hamster", "Animals", "type_animal_hamster", R.drawable.type_animal_hamster)
        addIcon("Hatching Chick", "Animals", "type_animal_hatching_chick", R.drawable.type_animal_hatching_chick)
        addIcon("Koala", "Animals", "type_animal_koala", R.drawable.type_animal_koala)
        addIcon("Lady Beetle", "Animals", "type_animal_lady_beetle", R.drawable.type_animal_lady_beetle)
        addIcon("Monkey", "Animals", "type_animal_monkey_face", R.drawable.type_animal_monkey_face)
        addIcon("Mosquito", "Animals", "type_animal_mosquito", R.drawable.type_animal_mosquito)
        addIcon("Mouse", "Animals", "type_animal_mouse_face", R.drawable.type_animal_mouse_face)
        addIcon("Octopus", "Animals", "type_animal_octopus", R.drawable.type_animal_octopus)
        addIcon("Ogre", "Animals", "type_animal_ogre", R.drawable.type_animal_ogre)
        addIcon("Orangutan", "Animals", "type_animal_orangutan", R.drawable.type_animal_orangutan)
        addIcon("Otter", "Animals", "type_animal_otter", R.drawable.type_animal_otter)
        addIcon("Owl", "Animals", "type_animal_owl", R.drawable.type_animal_owl)
        addIcon("Parrot", "Animals", "type_animal_parrot", R.drawable.type_animal_parrot)
        addIcon("Peacock", "Animals", "type_animal_peacock", R.drawable.type_animal_peacock)
        addIcon("Phoenix", "Animals", "type_animal_phoenix_bird", R.drawable.type_animal_phoenix_bird)
        addIcon("Pig", "Animals", "type_animal_pig", R.drawable.type_animal_pig)
        addIcon("Pig Face", "Animals", "type_animal_pig_face", R.drawable.type_animal_pig_face)
        addIcon("Polar Bear", "Animals", "type_animal_polar_bear", R.drawable.type_animal_polar_bear)
        addIcon("Rabbit", "Animals", "type_animal_rabbit_face", R.drawable.type_animal_rabbit_face)
        addIcon("Raccoon", "Animals", "type_animal_raccoon", R.drawable.type_animal_raccoon)
        addIcon("Whale", "Animals", "type_animal_spouting_whale", R.drawable.type_animal_spouting_whale)
        addIcon("Squid", "Animals", "type_animal_squid", R.drawable.type_animal_squid)
        addIcon("Wolf", "Animals", "type_animal_wolf", R.drawable.type_animal_wolf)

        // Beverages
        addIcon("Beer", "Beverages", "type_beverages_beer", R.drawable.type_beverages_beer)
        addIcon("Coffee", "Beverages", "type_beverages_coffee", R.drawable.type_beverages_coffee)
        addIcon("Tea", "Beverages", "type_beverages_tea", R.drawable.type_beverages_tea)
        addIcon("Wine", "Beverages", "type_beverages_wine_glass", R.drawable.type_beverages_wine_glass)
        addIcon("Cocktail", "Beverages", "type_beverages_cocktail_glass", R.drawable.type_beverages_cocktail_glass)
        addIcon("Beverages", "Beverages", "type_beverages_beverages", R.drawable.type_beverages_beverages)
        addIcon("Beverage Box", "Beverages", "type_beverages_beverage_box", R.drawable.type_beverages_beverage_box)
        addIcon("Champaign", "Beverages", "type_beverages_bottle_with_popping_cork", R.drawable.type_beverages_bottle_with_popping_cork)
        addIcon("Bubble Tea", "Beverages", "type_beverages_bubble_tea", R.drawable.type_beverages_bubble_tea)
        addIcon("Beer Mugs", "Beverages", "type_beverages_clinking_beer_mugs", R.drawable.type_beverages_clinking_beer_mugs)
        addIcon("Glasses", "Beverages", "type_beverages_clinking_glasses", R.drawable.type_beverages_clinking_glasses)
        addIcon("Sake", "Beverages", "type_beverages_sake", R.drawable.type_beverages_sake)
        addIcon("Teapot", "Beverages", "type_beverages_teapot", R.drawable.type_beverages_teapot)
        addIcon("Tropical Drink", "Beverages", "type_beverages_tropical_drink", R.drawable.type_beverages_tropical_drink)

        // Food
        addIcon("Hamburger", "Food", "type_food_hamburger", R.drawable.type_food_hamburger)
        addIcon("Pizza", "Food", "type_food_pizza", R.drawable.type_food_pizza)
        addIcon("Taco", "Food", "type_food_taco", R.drawable.type_food_taco)
        addIcon("Ramen", "Food", "type_food_ramen", R.drawable.type_food_ramen)
        addIcon("Sushi", "Food", "type_food_sushi", R.drawable.type_food_sushi)
        addIcon("Bacon", "Food", "type_food_bacon", R.drawable.type_food_bacon)
        addIcon("Bento", "Food", "type_food_bento_box", R.drawable.type_food_bento_box)
        addIcon("Burrito", "Food", "type_food_burrito", R.drawable.type_food_burrito)
        addIcon("Canned Food", "Food", "type_food_canned_food", R.drawable.type_food_canned_food)
        addIcon("Cooked Rice", "Food", "type_food_cooked_rice", R.drawable.type_food_cooked_rice)
        addIcon("Cooking", "Food", "type_food_cooking", R.drawable.type_food_cooking)
        addIcon("Curry Rice", "Food", "type_food_curry_rice", R.drawable.type_food_curry_rice)
        addIcon("Dining", "Food", "type_food_dining", R.drawable.type_food_dining)
        addIcon("Fondue", "Food", "type_food_fondue", R.drawable.type_food_fondue)
        addIcon("Fried Shrimp", "Food", "type_food_fried_shrimp", R.drawable.type_food_fried_shrimp)
        addIcon("Green Salad", "Food", "type_food_green_salad", R.drawable.type_food_green_salad)
        addIcon("Hotdog", "Food", "type_food_hot_dog", R.drawable.type_food_hot_dog)
        addIcon("Meat Bone", "Food", "type_food_meat_on_bone", R.drawable.type_food_meat_on_bone)
        addIcon("Oyster", "Food", "type_food_oyster", R.drawable.type_food_oyster)
        addIcon("Pot", "Food", "type_food_pot_of_food", R.drawable.type_food_pot_of_food)
        addIcon("Poultry leg", "Food", "type_food_poultry_leg", R.drawable.type_food_poultry_leg)
        addIcon("Rice Ball", "Food", "type_food_rice_ball", R.drawable.type_food_rice_ball)
        addIcon("Sandwich", "Food", "type_food_sandwich", R.drawable.type_food_sandwich)
        addIcon("Pan Food", "Food", "type_food_shallow_pan_of_food", R.drawable.type_food_shallow_pan_of_food)
        addIcon("Saghetti", "Food", "type_food_spaghetti", R.drawable.type_food_spaghetti)
        addIcon("Stuffed Flatbread", "Food", "type_food_stuffed_flatbread", R.drawable.type_food_stuffed_flatbread)
        addIcon("Takeout", "Food", "type_food_takeout", R.drawable.type_food_takeout)

        // Fruits
        addIcon("Apple", "Fruits", "type_fruit_red_apple", R.drawable.type_fruit_red_apple)
        addIcon("Banana", "Fruits", "type_fruit_banana", R.drawable.type_fruit_banana)
        addIcon("Strawberry", "Fruits", "type_fruit_strawberry", R.drawable.type_fruit_strawberry)
        addIcon("Grapes", "Fruits", "type_fruit_grapes", R.drawable.type_fruit_grapes)
        addIcon("Mango", "Fruits", "type_fruit_mango", R.drawable.type_fruit_mango)
        addIcon("Avocado", "Fruits", "type_fruit_avocado", R.drawable.type_fruit_avocado)
        addIcon("Tomato", "Fruits", "type_fruit_tomato", R.drawable.type_fruit_tomato)
        addIcon("Pineapple", "Fruits", "type_fruit_pineapple", R.drawable.type_fruit_pineapple)
        addIcon("Blueberries", "Fruits", "type_fruit_blueberries", R.drawable.type_fruit_blueberries)
        addIcon("Cherries", "Fruits", "type_fruit_cherries", R.drawable.type_fruit_cherries)
        addIcon("Chestnut", "Fruits", "type_fruit_chestnut", R.drawable.type_fruit_chestnut)
        addIcon("Coconut", "Fruits", "type_fruit_coconut", R.drawable.type_fruit_coconut)
        addIcon("Corn", "Fruits", "type_fruit_ear_of_corn", R.drawable.type_fruit_ear_of_corn)
        addIcon("Green Apple", "Fruits", "type_fruit_green_apple", R.drawable.type_fruit_green_apple)
        addIcon("Kiwi", "Fruits", "type_fruit_kiwi_fruit", R.drawable.type_fruit_kiwi_fruit)
        addIcon("Lemon", "Fruits", "type_fruit_lemon", R.drawable.type_fruit_lemon)
        addIcon("Lime", "Fruits", "type_fruit_lime", R.drawable.type_fruit_lime)
        addIcon("Melon", "Fruits", "type_fruit_melon", R.drawable.type_fruit_melon)
        addIcon("Olive", "Fruits", "type_fruit_olive", R.drawable.type_fruit_olive)
        addIcon("Peach", "Fruits", "type_fruit_peach", R.drawable.type_fruit_peach)
        addIcon("Pear", "Fruits", "type_fruit_pear", R.drawable.type_fruit_pear)
        addIcon("Tangerine", "Fruits", "type_fruit_tangerine", R.drawable.type_fruit_tangerine)

        // Groceries
        addIcon("Steak", "Groceries", "type_groceries_cut_of_meat", R.drawable.type_groceries_cut_of_meat)
        addIcon("Egg", "Groceries", "type_groceries_egg", R.drawable.type_groceries_egg)
        addIcon("Fish", "Groceries", "type_groceries_fish", R.drawable.type_groceries_fish)
        addIcon("Bread", "Groceries", "type_groceries_bread", R.drawable.type_groceries_bread)
        addIcon("Baby Milk", "Groceries", "type_groceries_baby_bottle", R.drawable.type_groceries_baby_bottle)
        addIcon("Milk", "Groceries", "type_groceries_glass_of_milk", R.drawable.type_groceries_glass_of_milk)
        addIcon("Baguette Bread", "Groceries", "type_groceries_baguette_bread", R.drawable.type_groceries_baguette_bread)
        addIcon("Basket", "Groceries", "type_groceries_basket", R.drawable.type_groceries_basket)
        addIcon("Butter", "Groceries", "type_groceries_butter", R.drawable.type_groceries_butter)
        addIcon("Basket", "Groceries", "type_groceries_cheese_wedge", R.drawable.type_groceries_cheese_wedge)
        addIcon("Flatbread", "Groceries", "type_groceries_flatbread", R.drawable.type_groceries_flatbread)
        addIcon("Soap", "Groceries", "type_groceries_soap", R.drawable.type_groceries_soap)
        addIcon("Candle", "Groceries", "type_groceries_candle", R.drawable.type_groceries_candle)
        addIcon("Lotion Bottle", "Groceries", "type_groceries_lotion_bottle", R.drawable.type_groceries_lotion_bottle)
        addIcon("Sponge", "Groceries", "type_groceries_sponge", R.drawable.type_groceries_sponge)
        addIcon("Spoon", "Groceries", "type_groceries_spoon", R.drawable.type_groceries_spoon)
        addIcon("Toothbrush", "Groceries", "type_groceries_toothbrush", R.drawable.type_groceries_toothbrush)

        // Shopping
        addIcon("Cart", "Shopping", "type_shopping_shopping_cart", R.drawable.type_shopping_shopping_cart)
        addIcon("Bag", "Shopping", "type_shopping_shopping_bags", R.drawable.type_shopping_shopping_bags)
        addIcon("Dress", "Shopping", "type_shopping_dress", R.drawable.type_shopping_dress)
        addIcon("Shirt", "Shopping", "type_shopping_t_shirt", R.drawable.type_shopping_t_shirt)
        addIcon("Jeans", "Shopping", "type_shopping_jeans", R.drawable.type_shopping_jeans)
        addIcon("Purse", "Shopping", "type_shopping_purse", R.drawable.type_shopping_purse, "Wallet")
        addIcon("Backpacks", "Shopping", "type_shopping_backpack", R.drawable.type_shopping_backpack)
        addIcon("Ballet Shoes", "Shopping", "type_shopping_ballet_shoes", R.drawable.type_shopping_ballet_shoes)
        addIcon("Bikini", "Shopping", "type_shopping_bikini", R.drawable.type_shopping_bikini)
        addIcon("Briefcase", "Shopping", "type_shopping_briefcase", R.drawable.type_shopping_briefcase)
        addIcon("Cap", "Shopping", "type_shopping_billed_cap", R.drawable.type_shopping_billed_cap)
        addIcon("Clutch Bag", "Shopping", "type_shopping_clutch_bag", R.drawable.type_shopping_clutch_bag)
        addIcon("Coat", "Shopping", "type_shopping_coat", R.drawable.type_shopping_coat)
        addIcon("Gem Stone", "Shopping", "type_shopping_gem_stone", R.drawable.type_shopping_gem_stone)
        addIcon("Glasses", "Shopping", "type_shopping_glasses", R.drawable.type_shopping_glasses)
        addIcon("Gloves", "Shopping", "type_shopping_gloves", R.drawable.type_shopping_gloves)
        addIcon("Goggles", "Shopping", "type_shopping_goggles", R.drawable.type_shopping_goggles)
        addIcon("Handbag", "Shopping", "type_shopping_handbag", R.drawable.type_shopping_handbag)
        addIcon("High Heeled Shoes", "Shopping", "type_shopping_high_heeled_shoe", R.drawable.type_shopping_high_heeled_shoe)
        addIcon("Hiking Boot", "Shopping", "type_shopping_hiking_boot", R.drawable.type_shopping_hiking_boot)
        addIcon("Kimono", "Shopping", "type_shopping_kimono", R.drawable.type_shopping_kimono)
        addIcon("Lab Coat", "Shopping", "type_shopping_lab_coat", R.drawable.type_shopping_lab_coat)
        addIcon("Lipstick", "Shopping", "type_shopping_lipstick", R.drawable.type_shopping_lipstick)
        addIcon("Shoes", "Shopping", "type_shopping_mans_shoe", R.drawable.type_shopping_mans_shoe)
        addIcon("Martial Arts", "Shopping", "type_shopping_martial_arts_uniform", R.drawable.type_shopping_martial_arts_uniform)
        addIcon("Nail Polish", "Shopping", "type_shopping_nail_polish", R.drawable.type_shopping_nail_polish)
        addIcon("Necktie", "Shopping", "type_shopping_necktie", R.drawable.type_shopping_necktie)
        addIcon("Swimsuit", "Shopping", "type_shopping_one_piece_swimsuit", R.drawable.type_shopping_one_piece_swimsuit)
        addIcon("Sari", "Shopping", "type_shopping_sari", R.drawable.type_shopping_sari)
        addIcon("Scarf", "Shopping", "type_shopping_scarf", R.drawable.type_shopping_scarf)
        addIcon("Shorts", "Shopping", "type_shopping_shorts", R.drawable.type_shopping_shorts)
        addIcon("Socks", "Shopping", "type_shopping_socks", R.drawable.type_shopping_socks)
        addIcon("Sunglasses", "Shopping", "type_shopping_sunglasses", R.drawable.type_shopping_sunglasses)
        addIcon("Top Hat", "Shopping", "type_shopping_top_hat", R.drawable.type_shopping_top_hat)

        // Finance
        addIcon("Bank", "Finance", "type_finance_bank", R.drawable.type_finance_bank)
        addIcon("Bill", "Finance", "type_finance_dollar_banknote", R.drawable.type_finance_dollar_banknote)
        addIcon("Chart", "Finance", "type_finance_bar_chart", R.drawable.type_finance_bar_chart)
        addIcon("Chart Decreasing", "Finance", "type_finance_chart_decreasing", R.drawable.type_finance_chart_decreasing)
        addIcon("Chart Increasing", "Finance", "type_finance_chart_increasing", R.drawable.type_finance_chart_increasing)
        addIcon("Coin", "Finance", "type_finance_coin", R.drawable.type_finance_coin)
        addIcon("Yen Chart", "Finance", "type_finance_chart_increasing_with_yen", R.drawable.type_finance_chart_increasing_with_yen)
        addIcon("Building", "Finance", "type_finance_classical_building", R.drawable.type_finance_classical_building)
        addIcon("Currency Exchange", "Finance", "type_finance_currency_exchange", R.drawable.type_finance_currency_exchange)
        addIcon("Euro", "Finance", "type_finance_euro_banknote", R.drawable.type_finance_euro_banknote)
        addIcon("Dollar Sign", "Finance", "type_finance_heavy_dollar_sign", R.drawable.type_finance_heavy_dollar_sign)
        addIcon("Money Bag", "Finance", "type_finance_money_bag", R.drawable.type_finance_money_bag)
        addIcon("Money Bag Wings", "Finance", "type_finance_money_with_wings", R.drawable.type_finance_money_with_wings)
        addIcon("Pound", "Finance", "type_finance_pound_banknote", R.drawable.type_finance_pound_banknote)
        addIcon("Yen", "Finance", "type_finance_yen_banknote", R.drawable.type_finance_yen_banknote)
        addIcon("Crypto", "Finance", "type_finance_crypto", R.drawable.type_finance_crypto)
        addIcon("Credit Card", "Finance", "type_finance_credit_card", R.drawable.type_finance_credit_card)
        addIcon("Deposit", "Finance", "type_finance_deposit", R.drawable.type_finance_deposit)
        addIcon("Insurance", "Finance", "type_finance_insurance", R.drawable.type_finance_insurance)
        addIcon("Tip", "Finance", "type_finance_tip", R.drawable.type_finance_tip)
        addIcon("Tax", "Finance", "type_finance_tax_due", R.drawable.type_finance_tax_due)

        // Travel
        addIcon("Airplane", "Travel", "type_travel_transport_airplane", R.drawable.type_travel_transport_airplane)
        addIcon("Bus", "Travel", "type_travel_transport_bus", R.drawable.type_travel_transport_bus)
        addIcon("Car", "Travel", "type_travel_transport_automobile", R.drawable.type_travel_transport_automobile)
        addIcon("Train", "Travel", "type_travel_transport_bullet_train", R.drawable.type_travel_transport_bullet_train)
        addIcon("Taxi", "Travel", "type_travel_transport_taxi", R.drawable.type_travel_transport_taxi)
        addIcon("Admission Tickets", "Travel", "type_travel_transport_admission_tickets", R.drawable.type_travel_transport_admission_tickets)
        addIcon("Aerial Tramway", "Travel", "type_travel_transport_aerial_tramway", R.drawable.type_travel_transport_aerial_tramway)
        addIcon("Airplane Arrival", "Travel", "type_travel_transport_airplane_arrival", R.drawable.type_travel_transport_airplane_arrival)
        addIcon("Airplane Departure", "Travel", "type_travel_transport_airplane_departure", R.drawable.type_travel_transport_airplane_departure)
        addIcon("Auto Rickshaw", "Travel", "type_travel_transport_auto_rickshaw", R.drawable.type_travel_transport_auto_rickshaw)
        addIcon("Canoe", "Travel", "type_travel_transport_canoe", R.drawable.type_travel_transport_canoe)
        addIcon("Delivery Truck", "Travel", "type_travel_transport_delivery_truck", R.drawable.type_travel_transport_delivery_truck)
        addIcon("Fuel Pump", "Travel", "type_travel_transport_fuel_pump", R.drawable.type_travel_transport_fuel_pump)
        addIcon("Globe", "Travel", "type_travel_transport_globe_showing_asia_australia", R.drawable.type_travel_transport_globe_showing_asia_australia)
        addIcon("Helicopter", "Travel", "type_travel_transport_helicopter", R.drawable.type_travel_transport_helicopter)
        addIcon("High Speed Train", "Travel", "type_travel_transport_high_speed_train", R.drawable.type_travel_transport_high_speed_train)
        addIcon("Inbox Tray", "Travel", "type_travel_transport_inbox_tray", R.drawable.type_travel_transport_inbox_tray)
        addIcon("Light Rail", "Travel", "type_travel_transport_light_rail", R.drawable.type_travel_transport_light_rail)
        addIcon("Luggage", "Travel", "type_travel_transport_luggage", R.drawable.type_travel_transport_luggage)
        addIcon("Metro", "Travel", "type_travel_transport_metro", R.drawable.type_travel_transport_metro)
        addIcon("Minibus", "Travel", "type_travel_transport_minibus", R.drawable.type_travel_transport_minibus)
        addIcon("Monorail", "Travel", "type_travel_transport_monorail", R.drawable.type_travel_transport_monorail)
        addIcon("Motor Boat", "Travel", "type_travel_transport_motor_boat", R.drawable.type_travel_transport_motor_boat)
        addIcon("Motor Scooter", "Travel", "type_travel_transport_motor_scooter", R.drawable.type_travel_transport_motor_scooter)
        addIcon("Motorcycle", "Travel", "type_travel_transport_motorcycle", R.drawable.type_travel_transport_motorcycle)
        addIcon("Mountain Cableway", "Travel", "type_travel_transport_mountain_cableway", R.drawable.type_travel_transport_mountain_cableway)
        addIcon("Mountain Railway", "Travel", "type_travel_transport_mountain_railway", R.drawable.type_travel_transport_mountain_railway)
        addIcon("Oncoming Automobile", "Travel", "type_travel_transport_oncoming_automobile", R.drawable.type_travel_transport_oncoming_automobile)
        addIcon("Oncoming Bus", "Travel", "type_travel_transport_oncoming_bus", R.drawable.type_travel_transport_oncoming_bus)
        addIcon("Oncoming taxi", "Travel", "type_travel_transport_oncoming_taxi", R.drawable.type_travel_transport_oncoming_taxi)
        addIcon("Oncoming Police Car", "Travel", "type_travel_transport_oncoming_police_car", R.drawable.type_travel_transport_oncoming_police_car)
        addIcon("Mailbox", "Travel", "type_travel_transport_open_mailbox_with_lowered_flag", R.drawable.type_travel_transport_open_mailbox_with_lowered_flag)
        addIcon("Mailbox Flag", "Travel", "type_travel_transport_open_mailbox_with_raised_flag", R.drawable.type_travel_transport_open_mailbox_with_raised_flag)
        addIcon("Outbox Tray", "Travel", "type_travel_transport_outbox_tray", R.drawable.type_travel_transport_outbox_tray)
        addIcon("Package", "Travel", "type_travel_transport_package", R.drawable.type_travel_transport_package)
        addIcon("Ship", "Travel", "type_travel_transport_passenger_ship", R.drawable.type_travel_transport_passenger_ship)
        addIcon("Pickup Truck", "Travel", "type_travel_transport_pickup_truck", R.drawable.type_travel_transport_pickup_truck)
        addIcon("Small Airplane", "Travel", "type_travel_transport_small_airplane", R.drawable.type_travel_transport_small_airplane)
        addIcon("Speedboat", "Travel", "type_travel_transport_speedboat", R.drawable.type_travel_transport_speedboat)
        addIcon("Tickets", "Travel", "type_travel_transport_ticket", R.drawable.type_travel_transport_ticket)
        addIcon("Inventory", "Travel", "type_travel_transport_inventory", R.drawable.type_travel_transport_inventory)

        // Health
        addIcon("Hospital", "Health", "type_health_hospital", R.drawable.type_health_hospital)
        addIcon("Pill", "Health", "type_health_pill", R.drawable.type_health_pill)
        addIcon("Stethoscope", "Health", "type_health_stethoscope", R.drawable.type_health_stethoscope)
        addIcon("DNA", "Health", "type_health_dna", R.drawable.type_health_dna)
        addIcon("Tooth", "Health", "type_health_tooth", R.drawable.type_health_tooth)
        addIcon("Bandage", "Health", "type_health_adhesive_bandage", R.drawable.type_health_adhesive_bandage)
        addIcon("Ambulance", "Health", "type_health_ambulance", R.drawable.type_health_ambulance)
        addIcon("Cigarette", "Health", "type_health_cigarette", R.drawable.type_health_cigarette)
        addIcon("Blood", "Health", "type_health_drop_of_blood", R.drawable.type_health_drop_of_blood)
        addIcon("Health Worker", "Health", "type_health_health_worker_light", R.drawable.type_health_health_worker_light)
        addIcon("Mending Heart", "Health", "type_health_mending_heart", R.drawable.type_health_mending_heart)
        addIcon("Syringe", "Health", "type_health_syringe", R.drawable.type_health_syringe)
        addIcon("Thermometer", "Health", "type_health_thermometer", R.drawable.type_health_thermometer)
        addIcon("X-ray", "Health", "type_health_x_ray", R.drawable.type_health_x_ray)
        addIcon("Vet", "Health", "type_health_vet", R.drawable.type_health_vet)

        // Tools
        addIcon("Game", "Tools", "type_tool_electronic_video_game", R.drawable.type_tool_electronic_video_game)
        addIcon("Movie", "Tools", "type_tool_electronic_movie_camera", R.drawable.type_tool_electronic_movie_camera)
        addIcon("Music", "Tools", "type_tool_electronic_headphone", R.drawable.type_tool_electronic_headphone, "Headphone")
        addIcon("Movie Clapper", "Tools", "type_tool_electronic_clapper_board", R.drawable.type_tool_electronic_clapper_board)
        addIcon("Axe", "Tools", "type_tool_electronic_axe", R.drawable.type_tool_electronic_axe)
        addIcon("Alarm Clock", "Tools", "type_tool_electronic_alarm_clock", R.drawable.type_tool_electronic_alarm_clock)
        addIcon("Ballot Box", "Tools", "type_tool_electronic_ballot_box_with_ballot", R.drawable.type_tool_electronic_ballot_box_with_ballot)
        addIcon("Camera", "Tools", "type_tool_electronic_camera", R.drawable.type_tool_electronic_camera)
        addIcon("Camera Flash", "Tools", "type_tool_electronic_camera_with_flash", R.drawable.type_tool_electronic_camera_with_flash)
        addIcon("Carpentry Saw", "Tools", "type_tool_electronic_carpentry_saw", R.drawable.type_tool_electronic_carpentry_saw)
        addIcon("Chopsticks", "Tools", "type_tool_electronic_chopsticks", R.drawable.type_tool_electronic_chopsticks)
        addIcon("Clock", "Tools", "type_tool_electronic_clock", R.drawable.type_tool_electronic_clock)
        addIcon("Compass", "Tools", "type_tool_electronic_compass", R.drawable.type_tool_electronic_compass)
        addIcon("Computer Disk", "Tools", "type_tool_electronic_computer_disk", R.drawable.type_tool_electronic_computer_disk)
        addIcon("Computer Mouse", "Tools", "type_tool_electronic_computer_mouse", R.drawable.type_tool_electronic_computer_mouse)
        addIcon("Dagger", "Tools", "type_tool_electronic_dagger", R.drawable.type_tool_electronic_dagger)
        addIcon("Desktop", "Tools", "type_tool_electronic_desktop_computer", R.drawable.type_tool_electronic_desktop_computer)
        addIcon("DVD", "Tools", "type_tool_electronic_dvd", R.drawable.type_tool_electronic_dvd)
        addIcon("Fax Machine", "Tools", "type_tool_electronic_fax_machine", R.drawable.type_tool_electronic_fax_machine)
        addIcon("Film Frames", "Tools", "type_tool_electronic_film_frames", R.drawable.type_tool_electronic_film_frames)
        addIcon("Film Projectors", "Tools", "type_tool_electronic_film_projector", R.drawable.type_tool_electronic_film_projector)
        addIcon("Flashlight", "Tools", "type_tool_electronic_flashlight", R.drawable.type_tool_electronic_flashlight)
        addIcon("Floppy Disk", "Tools", "type_tool_electronic_floppy_disk", R.drawable.type_tool_electronic_floppy_disk)
        addIcon("Flower Card", "Tools", "type_tool_electronic_flower_playing_cards", R.drawable.type_tool_electronic_flower_playing_cards)
        addIcon("Gear", "Tools", "type_tool_electronic_gear", R.drawable.type_tool_electronic_gear)
        addIcon("Hammer", "Tools", "type_tool_electronic_hammer", R.drawable.type_tool_electronic_hammer)
        addIcon("Hammer Pick", "Tools", "type_tool_electronic_hammer_and_pick", R.drawable.type_tool_electronic_hammer_and_pick)
        addIcon("Hammer Wrench", "Tools", "type_tool_electronic_hammer_and_wrench", R.drawable.type_tool_electronic_hammer_and_wrench)
        addIcon("High Voltage", "Tools", "type_tool_electronic_high_voltage", R.drawable.type_tool_electronic_high_voltage)
        addIcon("Hour Glass", "Tools", "type_tool_electronic_hourglass_not_done", R.drawable.type_tool_electronic_hourglass_not_done)
        addIcon("Joystick", "Tools", "type_tool_electronic_joystick", R.drawable.type_tool_electronic_joystick)
        addIcon("Key", "Tools", "type_tool_electronic_key", R.drawable.type_tool_electronic_key)
        addIcon("Knife", "Tools", "type_tool_electronic_kitchen_knife", R.drawable.type_tool_electronic_kitchen_knife)
        addIcon("Ladder", "Tools", "type_tool_electronic_ladder", R.drawable.type_tool_electronic_ladder)
        addIcon("Laptop", "Tools", "type_tool_electronic_laptop", R.drawable.type_tool_electronic_laptop)
        addIcon("Level Slider", "Tools", "type_tool_electronic_level_slider", R.drawable.type_tool_electronic_level_slider)
        addIcon("Bulb", "Tools", "type_tool_electronic_light_bulb", R.drawable.type_tool_electronic_light_bulb)
        addIcon("Lock Key", "Tools", "type_tool_electronic_locked_with_key", R.drawable.type_tool_electronic_locked_with_key)
        addIcon("Loudspeaker", "Tools", "type_tool_electronic_loudspeaker", R.drawable.type_tool_electronic_loudspeaker)
        addIcon("Magnifying Glass left", "Tools", "type_tool_electronic_magnifying_glass_tilted_left", R.drawable.type_tool_electronic_magnifying_glass_tilted_left)
        addIcon("Magnifying Glass right", "Tools", "type_tool_electronic_magnifying_glass_tilted_right", R.drawable.type_tool_electronic_magnifying_glass_tilted_right)
        addIcon("Megaphone", "Tools", "type_tool_electronic_megaphone", R.drawable.type_tool_electronic_megaphone)
        addIcon("Microphone", "Tools", "type_tool_electronic_microphone", R.drawable.type_tool_electronic_microphone)
        addIcon("Mobile", "Tools", "type_tool_electronic_mobile_phone", R.drawable.type_tool_electronic_mobile_phone)
        addIcon("Nut Bolt", "Tools", "type_tool_electronic_nut_and_bolt", R.drawable.type_tool_electronic_nut_and_bolt)
        addIcon("Old Key", "Tools", "type_tool_electronic_old_key", R.drawable.type_tool_electronic_old_key)
        addIcon("One OClock", "Tools", "type_tool_electronic_one_oclock", R.drawable.type_tool_electronic_one_oclock)
        addIcon("Optical Disk", "Tools", "type_tool_electronic_optical_disk", R.drawable.type_tool_electronic_optical_disk)
        addIcon("Pick", "Tools", "type_tool_electronic_pick", R.drawable.type_tool_electronic_pick)
        addIcon("Printer", "Tools", "type_tool_electronic_printer", R.drawable.type_tool_electronic_printer)
        addIcon("Scissors", "Tools", "type_tool_electronic_scissors", R.drawable.type_tool_electronic_scissors)
        addIcon("Screwdriver", "Tools", "type_tool_electronic_screwdriver", R.drawable.type_tool_electronic_screwdriver)
        addIcon("Stopwatch", "Tools", "type_tool_electronic_stopwatch", R.drawable.type_tool_electronic_stopwatch)
        addIcon("Studio Microphone", "Tools", "type_tool_electronic_studio_microphone", R.drawable.type_tool_electronic_studio_microphone)
        addIcon("Telephone", "Tools", "type_tool_electronic_telephone", R.drawable.type_tool_electronic_telephone)
        addIcon("Telescope", "Tools", "type_tool_electronic_telescope", R.drawable.type_tool_electronic_telescope)
        addIcon("Toolbox", "Tools", "type_tool_electronic_toolbox", R.drawable.type_tool_electronic_toolbox)
        addIcon("Cassette", "Tools", "type_tool_electronic_videocassette", R.drawable.type_tool_electronic_videocassette)
        addIcon("Watch", "Tools", "type_tool_electronic_watch", R.drawable.type_tool_electronic_watch)
        addIcon("Wrench", "Tools", "type_tool_electronic_wrench", R.drawable.type_tool_electronic_wrench)
        addIcon("Software", "Tools", "type_tool_electronic_software", R.drawable.type_tool_electronic_software)

        // Vegetables
        addIcon("Beans", "Vegetables", "type_vegetable_beans", R.drawable.type_vegetable_beans)
        addIcon("Bell Pepper", "Vegetables", "type_vegetable_bell_pepper", R.drawable.type_vegetable_bell_pepper)
        addIcon("Broccoli", "Vegetables", "type_vegetable_broccoli", R.drawable.type_vegetable_broccoli)
        addIcon("Carrot", "Vegetables", "type_vegetable_carrot", R.drawable.type_vegetable_carrot)
        addIcon("Cucumber", "Vegetables", "type_vegetable_cucumber", R.drawable.type_vegetable_cucumber)
        addIcon("Eggplant", "Vegetables", "type_vegetable_eggplant", R.drawable.type_vegetable_eggplant)
        addIcon("Garlic", "Vegetables", "type_vegetable_garlic", R.drawable.type_vegetable_garlic)
        addIcon("Ginger", "Vegetables", "type_vegetable_ginger_root", R.drawable.type_vegetable_ginger_root)
        addIcon("Hot Pepper", "Vegetables", "type_vegetable_hot_pepper", R.drawable.type_vegetable_hot_pepper)
        addIcon("Brown Mushroom", "Vegetables", "type_vegetable_brown_mushroom", R.drawable.type_vegetable_brown_mushroom)
        addIcon("Mushroom", "Vegetables", "type_vegetable_mushroom", R.drawable.type_vegetable_mushroom)
        addIcon("Onion", "Vegetables", "type_vegetable_onion", R.drawable.type_vegetable_onion)
        addIcon("Pea Pod", "Vegetables", "type_vegetable_pea_pod", R.drawable.type_vegetable_pea_pod)
        addIcon("Potato", "Vegetables", "type_vegetable_potato", R.drawable.type_vegetable_potato)

        // Snacks
        addIcon("Cookie", "Snacks", "type_snack_cookie", R.drawable.type_snack_cookie)
        addIcon("Dumpling", "Snacks", "type_snack_dumpling", R.drawable.type_snack_dumpling)
        addIcon("Fortune Cookie", "Snacks", "type_snack_fortune_cookie", R.drawable.type_snack_fortune_cookie)
        addIcon("French Fries", "Snacks", "type_snack_french_fries", R.drawable.type_snack_french_fries)
        addIcon("Peanuts", "Snacks", "type_snack_peanuts", R.drawable.type_snack_peanuts)
        addIcon("Popcorn", "Snacks", "type_snack_popcorn", R.drawable.type_snack_popcorn)
        addIcon("Rice Cracker", "Snacks", "type_snack_rice_cracker", R.drawable.type_snack_rice_cracker)
        addIcon("Fish Cake", "Snacks", "type_snack_fish_cake_with_swirl", R.drawable.type_snack_fish_cake_with_swirl)

        // Sweets
        addIcon("Candy", "Sweets", "type_sweet_candy", R.drawable.type_sweet_candy)
        addIcon("Chocolate Bar", "Sweets", "type_sweet_chocolate_bar", R.drawable.type_sweet_chocolate_bar)
        addIcon("Cupcake", "Sweets", "type_sweet_cupcake", R.drawable.type_sweet_cupcake)
        addIcon("Doughnut", "Sweets", "type_sweet_doughnut", R.drawable.type_sweet_doughnut)
        addIcon("Ice Cream", "Sweets", "type_sweet_ice_cream", R.drawable.type_sweet_ice_cream)
        addIcon("Shaved Ice", "Sweets", "type_sweet_shaved_ice", R.drawable.type_sweet_shaved_ice)
        addIcon("Soft Ice Cream", "Sweets", "type_sweet_soft_ice_cream", R.drawable.type_sweet_soft_ice_cream)
        addIcon("Lollipop", "Sweets", "type_sweet_lollipop", R.drawable.type_sweet_lollipop)
        addIcon("Pancakes", "Sweets", "type_sweet_pancakes", R.drawable.type_sweet_pancakes)
        addIcon("Pie", "Sweets", "type_sweet_pie", R.drawable.type_sweet_pie)
        addIcon("Shortcake", "Sweets", "type_sweet_shortcake", R.drawable.type_sweet_shortcake)
        addIcon("Waffle", "Sweets", "type_sweet_waffle", R.drawable.type_sweet_waffle)
        addIcon("Bagel", "Sweets", "type_sweet_bagel", R.drawable.type_sweet_bagel)
        addIcon("Birthday Cake", "Sweets", "type_sweet_birthday_cake", R.drawable.type_sweet_birthday_cake)
        addIcon("Croissant", "Sweets", "type_sweet_croissant", R.drawable.type_sweet_croissant)
        addIcon("Custard", "Sweets", "type_sweet_custard", R.drawable.type_sweet_custard)
        addIcon("Dango", "Sweets", "type_sweet_dango", R.drawable.type_sweet_dango)
        addIcon("Falafel", "Sweets", "type_sweet_falafel", R.drawable.type_sweet_falafel)
        addIcon("Honey Pot", "Sweets", "type_sweet_honey_pot", R.drawable.type_sweet_honey_pot)
        addIcon("Oden", "Sweets", "type_sweet_oden", R.drawable.type_sweet_oden)
        addIcon("Roasted Sweet Potato", "Sweets", "type_sweet_roasted_sweet_potato", R.drawable.type_sweet_roasted_sweet_potato)

        // Sports
        addIcon("Badminton", "Sports", "type_sports_badminton", R.drawable.type_sports_badminton)
        addIcon("Baseball", "Sports", "type_sports_baseball", R.drawable.type_sports_baseball)
        addIcon("Basketball", "Sports", "type_sports_basketball", R.drawable.type_sports_basketball)
        addIcon("Cricket", "Sports", "type_sports_cricket_game", R.drawable.type_sports_cricket_game)
        addIcon("Field Hockey", "Sports", "type_sports_field_hockey", R.drawable.type_sports_field_hockey, "Hockey")
        addIcon("Football", "Sports", "type_sports_american_football", R.drawable.type_sports_american_football)
        addIcon("Golf", "Sports", "type_sports_flag_in_hole", R.drawable.type_sports_flag_in_hole)
        addIcon("Ping Pong", "Sports", "type_sports_ping_pong", R.drawable.type_sports_ping_pong, "PingPong")
        addIcon("Soccer Ball", "Sports", "type_sports_soccer_ball", R.drawable.type_sports_soccer_ball)
        addIcon("SoftBall", "Sports", "type_sports_softball", R.drawable.type_sports_softball)
        addIcon("Tennis", "Sports", "type_sports_tennis", R.drawable.type_sports_tennis)
        addIcon("Trophy", "Sports", "type_sports_trophy", R.drawable.type_sports_trophy)
        addIcon("Sports Medal", "Sports", "type_sports_sports_medal", R.drawable.type_sports_sports_medal)
        addIcon("Military Medal", "Sports", "type_sports_military_medal", R.drawable.type_sports_military_medal)
        addIcon("1st place medal", "Sports", "type_sports_1st_place_medal", R.drawable.type_sports_1st_place_medal)
        addIcon("2nd place medal", "Sports", "type_sports_2nd_place_medal", R.drawable.type_sports_2nd_place_medal)
        addIcon("3rd place medal", "Sports", "type_sports_3rd_place_medal", R.drawable.type_sports_3rd_place_medal)
        addIcon("Boomerang", "Sports", "type_sports_boomerang", R.drawable.type_sports_boomerang)
        addIcon("Bow and Arrow", "Sports", "type_sports_bow_and_arrow", R.drawable.type_sports_bow_and_arrow)
        addIcon("Bowling", "Sports", "type_sports_bowling", R.drawable.type_sports_bowling)
        addIcon("Boxing", "Sports", "type_sports_boxing_glove", R.drawable.type_sports_boxing_glove)
        addIcon("Bullseye", "Sports", "type_sports_bullseye", R.drawable.type_sports_bullseye)
        addIcon("Chequered Flag", "Sports", "type_sports_chequered_flag", R.drawable.type_sports_chequered_flag)
        addIcon("Chess", "Sports", "type_sports_chess_pawn", R.drawable.type_sports_chess_pawn)
        addIcon("Diving", "Sports", "type_sports_diving_mask", R.drawable.type_sports_diving_mask)
        addIcon("Fishing", "Sports", "type_sports_fishing_pole", R.drawable.type_sports_fishing_pole)
        addIcon("Biceps Arms", "Sports", "type_sports_flexed_biceps_light", R.drawable.type_sports_flexed_biceps_light)
        addIcon("Die", "Sports", "type_sports_game_die", R.drawable.type_sports_game_die)
        addIcon("Ice Hockey", "Sports", "type_sports_ice_hockey", R.drawable.type_sports_ice_hockey)
        addIcon("Ice Skate", "Sports", "type_sports_ice_skate", R.drawable.type_sports_ice_skate)
        addIcon("Lacrosse", "Sports", "type_sports_lacrosse", R.drawable.type_sports_lacrosse)
        addIcon("Gym", "Sports", "type_sports_man_lifting_weights", R.drawable.type_sports_man_lifting_weights)
        addIcon("Gym Women", "Sports", "type_sports_woman_lifting_weights", R.drawable.type_sports_woman_lifting_weights)
        addIcon("Mechanical Arm", "Sports", "type_sports_mechanical_arm", R.drawable.type_sports_mechanical_arm)
        addIcon("Pool Ball", "Sports", "type_sports_pool_8_ball", R.drawable.type_sports_pool_8_ball)
        addIcon("Rugby", "Sports", "type_sports_rugby_football", R.drawable.type_sports_rugby_football)
        addIcon("Skateboard", "Sports", "type_sports_skateboard", R.drawable.type_sports_skateboard)
        addIcon("Snowboard", "Sports", "type_sports_snowboarder_light", R.drawable.type_sports_snowboarder_light)
        addIcon("Volleyball", "Sports", "type_sports_volleyball", R.drawable.type_sports_volleyball)

        // Stationery
        addIcon("Pencil", "Stationery", "type_stationary_pencil", R.drawable.type_stationary_pencil)
        addIcon("Pen", "Stationery", "type_stationary_pen", R.drawable.type_stationary_pen)
        addIcon("Fountain Pen", "Stationery", "type_stationary_fountain_pen", R.drawable.type_stationary_fountain_pen)
        addIcon("Paintbrush", "Stationery", "type_stationary_paintbrush", R.drawable.type_stationary_paintbrush)
        addIcon("Notebook", "Stationery", "type_stationary_notebook", R.drawable.type_stationary_notebook)
        addIcon("Notebook Decorative", "Stationery", "type_stationary_notebook_with_decorative_cover", R.drawable.type_stationary_notebook_with_decorative_cover)
        addIcon("Books", "Stationery", "type_stationary_books", R.drawable.type_stationary_books)
        addIcon("Closed Book", "Stationery", "type_stationary_closed_book", R.drawable.type_stationary_closed_book)
        addIcon("Green Book", "Stationery", "type_stationary_green_book", R.drawable.type_stationary_green_book)
        addIcon("Blue Book", "Stationery", "type_stationary_blue_book", R.drawable.type_stationary_blue_book)
        addIcon("Orange Book", "Stationery", "type_stationary_orange_book", R.drawable.type_stationary_orange_book)
        addIcon("Open Book", "Stationery", "type_stationary_open_book", R.drawable.type_stationary_open_book)
        addIcon("Ledger", "Stationery", "type_stationary_ledger", R.drawable.type_stationary_ledger)
        addIcon("Paperclip", "Stationery", "type_stationary_paperclip", R.drawable.type_stationary_paperclip)
        addIcon("Ruler", "Stationery", "type_stationary_straight_ruler", R.drawable.type_stationary_straight_ruler)
        addIcon("Artist Palette", "Stationery", "type_stationary_artist_palette", R.drawable.type_stationary_artist_palette)
        addIcon("Bookmark", "Stationery", "type_stationary_bookmark", R.drawable.type_stationary_bookmark)
        addIcon("Label", "Stationery", "type_stationary_label", R.drawable.type_stationary_label)
        addIcon("Bookmark Tabs", "Stationery", "type_stationary_bookmark_tabs", R.drawable.type_stationary_bookmark_tabs)
        addIcon("Files Box", "Stationery", "type_stationary_card_file_box", R.drawable.type_stationary_card_file_box)
        addIcon("Card Index", "Stationery", "type_stationary_card_index", R.drawable.type_stationary_card_index)
        addIcon("Clipboard", "Stationery", "type_stationary_clipboard", R.drawable.type_stationary_clipboard)
        addIcon("Link", "Stationery", "type_stationary_link", R.drawable.type_stationary_link)
        addIcon("Link Paperclips", "Stationery", "type_stationary_linked_paperclips", R.drawable.type_stationary_linked_paperclips)
        addIcon("Memo", "Stationery", "type_stationary_memo", R.drawable.type_stationary_memo)
        addIcon("Musical score", "Stationery", "type_stationary_musical_score", R.drawable.type_stationary_musical_score)
        addIcon("Newspaper", "Stationery", "type_stationary_newspaper", R.drawable.type_stationary_newspaper)
        addIcon("Page", "Stationery", "type_stationary_page_facing_up", R.drawable.type_stationary_page_facing_up)
        addIcon("page Curl", "Stationery", "type_stationary_page_with_curl", R.drawable.type_stationary_page_with_curl)
        addIcon("Scroll", "Stationery", "type_stationary_scroll", R.drawable.type_stationary_scroll)
        addIcon("Spiral notepad", "Stationery", "type_stationary_spiral_notepad", R.drawable.type_stationary_spiral_notepad)
        addIcon("Pushpin", "Stationery", "type_stationary_pushpin", R.drawable.type_stationary_pushpin)
        addIcon("Reminder Ribbon", "Stationery", "type_stationary_reminder_ribbon", R.drawable.type_stationary_reminder_ribbon)
        addIcon("Ribbon", "Stationery", "type_stationary_ribbon", R.drawable.type_stationary_ribbon)
        addIcon("Wrapped Gift", "Stationery", "type_stationary_wrapped_gift", R.drawable.type_stationary_wrapped_gift)
        addIcon("Writing hand", "Stationery", "type_stationary_writing_hand_light", R.drawable.type_stationary_writing_hand_light)
        addIcon("Toys", "Stationery", "type_stationary_toys", R.drawable.type_stationary_toys)
        addIcon("Gift Card", "Stationery", "type_stationary_gift_card", R.drawable.type_stationary_gift_card)

        // Musical Instruments
        addIcon("Guitar", "Musical Instruments", "type_musical_instrument_guitar", R.drawable.type_musical_instrument_guitar)
        addIcon("Keyboard", "Musical Instruments", "type_musical_instrument_musical_keyboard", R.drawable.type_musical_instrument_musical_keyboard)
        addIcon("Saxophone", "Musical Instruments", "type_musical_instrument_saxophone", R.drawable.type_musical_instrument_saxophone)
        addIcon("Trumpet", "Musical Instruments", "type_musical_instrument_trumpet", R.drawable.type_musical_instrument_trumpet)
        addIcon("Violin", "Musical Instruments", "type_musical_instrument_violin", R.drawable.type_musical_instrument_violin)
        addIcon("Banjo", "Musical Instruments", "type_musical_instrument_banjo", R.drawable.type_musical_instrument_banjo)
        addIcon("Flute", "Musical Instruments", "type_musical_instrument_flute", R.drawable.type_musical_instrument_flute)
        addIcon("Accordion", "Musical Instruments", "type_musical_instrument_accordion", R.drawable.type_musical_instrument_accordion)
        addIcon("Drum", "Musical Instruments", "type_event_and_place_drum", R.drawable.type_event_and_place_drum)

        // Flowers & Nature
        addIcon("Blossom", "Flowers & Nature", "type_flower_and_tree_blossom", R.drawable.type_flower_and_tree_blossom)
        addIcon("Cactus", "Flowers & Nature", "type_flower_and_tree_cactus", R.drawable.type_flower_and_tree_cactus)
        addIcon("Cherry Blossom", "Flowers & Nature", "type_flower_and_tree_cherry_blossom", R.drawable.type_flower_and_tree_cherry_blossom)
        addIcon("Hibiscus", "Flowers & Nature", "type_flower_and_tree_hibiscus", R.drawable.type_flower_and_tree_hibiscus)
        addIcon("Sunflower", "Flowers & Nature", "type_flower_and_tree_sunflower", R.drawable.type_flower_and_tree_sunflower)
        addIcon("Tulip", "Flowers & Nature", "type_flower_and_tree_tulip", R.drawable.type_flower_and_tree_tulip)
        addIcon("Palm Tree", "Flowers & Nature", "type_flower_and_tree_palm_tree", R.drawable.type_flower_and_tree_palm_tree)
        addIcon("Evergreen Tree", "Flowers & Nature", "type_flower_and_tree_evergreen_tree", R.drawable.type_flower_and_tree_evergreen_tree)
        addIcon("Deciduous Tree", "Flowers & Nature", "type_flower_and_tree_deciduous_tree", R.drawable.type_flower_and_tree_deciduous_tree, "Tree")
        addIcon("Bouquet", "Flowers & Nature", "type_flower_and_tree_bouquet", R.drawable.type_flower_and_tree_bouquet)
        addIcon("Four Clover", "Flowers & Nature", "type_flower_and_tree_four_leaf_clover", R.drawable.type_flower_and_tree_four_leaf_clover)
        addIcon("Herb", "Flowers & Nature", "type_flower_and_tree_herb", R.drawable.type_flower_and_tree_herb)
        addIcon("Hyacinth", "Flowers & Nature", "type_flower_and_tree_hyacinth", R.drawable.type_flower_and_tree_hyacinth)
        addIcon("Leafs", "Flowers & Nature", "type_flower_and_tree_leaf_fluttering_in_wind", R.drawable.type_flower_and_tree_leaf_fluttering_in_wind)
        addIcon("Leafy Green", "Flowers & Nature", "type_flower_and_tree_leafy_green", R.drawable.type_flower_and_tree_leafy_green)
        addIcon("Lotus", "Flowers & Nature", "type_flower_and_tree_lotus", R.drawable.type_flower_and_tree_lotus)
        addIcon("Maple Leaf", "Flowers & Nature", "type_flower_and_tree_maple_leaf", R.drawable.type_flower_and_tree_maple_leaf)
        addIcon("Pine", "Flowers & Nature", "type_flower_and_tree_pine_decoration", R.drawable.type_flower_and_tree_pine_decoration)
        addIcon("Potted Plant", "Flowers & Nature", "type_flower_and_tree_potted_plant", R.drawable.type_flower_and_tree_potted_plant)
        addIcon("Tanabata Tree", "Flowers & Nature", "type_flower_and_tree_tanabata_tree", R.drawable.type_flower_and_tree_tanabata_tree)
        addIcon("White Flower", "Flowers & Nature", "type_flower_and_tree_white_flower", R.drawable.type_flower_and_tree_white_flower)

        // Events & Places
        addIcon("House", "Events & Places", "type_event_and_place_house", R.drawable.type_event_and_place_house)
        addIcon("Houses", "Events & Places", "type_event_and_place_houses", R.drawable.type_event_and_place_houses)
        addIcon("Hotel", "Events & Places", "type_event_and_place_hotel", R.drawable.type_event_and_place_hotel)
        addIcon("House Garden", "Events & Places", "type_event_and_place_house_with_garden", R.drawable.type_event_and_place_house_with_garden)
        addIcon("Hut", "Events & Places", "type_event_and_place_hut", R.drawable.type_event_and_place_hut)
        addIcon("Love Hotel", "Events & Places", "type_event_and_place_love_hotel", R.drawable.type_event_and_place_love_hotel)
        addIcon("Wedding", "Events & Places", "type_event_and_place_wedding", R.drawable.type_event_and_place_wedding)
        addIcon("Party Popper", "Events & Places", "type_event_and_place_party_popper", R.drawable.type_event_and_place_party_popper)
        addIcon("Confetti Ball", "Events & Places", "type_event_and_place_confetti_ball", R.drawable.type_event_and_place_confetti_ball)
        addIcon("Magic", "Events & Places", "type_event_and_place_magic_wand", R.drawable.type_event_and_place_magic_wand)
        addIcon("Fireworks", "Events & Places", "type_event_and_place_fireworks", R.drawable.type_event_and_place_fireworks)
        addIcon("Firecracker", "Events & Places", "type_event_and_place_firecracker", R.drawable.type_event_and_place_firecracker)
        addIcon("Stadium", "Events & Places", "type_event_and_place_stadium", R.drawable.type_event_and_place_stadium)
        addIcon("Bell", "Events & Places", "type_event_and_place_bell", R.drawable.type_event_and_place_bell)
        addIcon("Camping", "Events & Places", "type_event_and_place_camping", R.drawable.type_event_and_place_camping)
        addIcon("Castle", "Events & Places", "type_event_and_place_castle", R.drawable.type_event_and_place_castle)
        addIcon("Church", "Events & Places", "type_event_and_place_church", R.drawable.type_event_and_place_church)
        addIcon("Hindu Temple", "Events & Places", "type_event_and_place_hindu_temple", R.drawable.type_event_and_place_hindu_temple)
        addIcon("Mosque", "Events & Places", "type_event_and_place_mosque", R.drawable.type_event_and_place_mosque)
        addIcon("Circus", "Events & Places", "type_event_and_place_circus_tent", R.drawable.type_event_and_place_circus_tent)
        addIcon("Cityscape", "Events & Places", "type_event_and_place_cityscape", R.drawable.type_event_and_place_cityscape)
        addIcon("Cityscape Dusk", "Events & Places", "type_event_and_place_cityscape_at_dusk", R.drawable.type_event_and_place_cityscape_at_dusk)
        addIcon("Convenience Store", "Events & Places", "type_event_and_place_convenience_store", R.drawable.type_event_and_place_convenience_store)
        addIcon("Department Store", "Events & Places", "type_event_and_place_department_store", R.drawable.type_event_and_place_department_store)
        addIcon("Couch Lamp", "Events & Places", "type_event_and_place_couch_and_lamp", R.drawable.type_event_and_place_couch_and_lamp)
        addIcon("Desert", "Events & Places", "type_event_and_place_desert", R.drawable.type_event_and_place_desert)
        addIcon("Desert Island", "Events & Places", "type_event_and_place_desert_island", R.drawable.type_event_and_place_desert_island)
        addIcon("Diwali Diya", "Events & Places", "type_event_and_place_diya_lamp", R.drawable.type_event_and_place_diya_lamp)
        addIcon("Christmas Tree", "Events & Places", "type_event_and_place_christmas_tree", R.drawable.type_event_and_place_christmas_tree)
        addIcon("Factory", "Events & Places", "type_event_and_place_factory", R.drawable.type_event_and_place_factory)
        addIcon("Ferris Wheel", "Events & Places", "type_event_and_place_ferris_wheel", R.drawable.type_event_and_place_ferris_wheel)
        addIcon("Graduation", "Events & Places", "type_event_and_place_graduation_cap", R.drawable.type_event_and_place_graduation_cap)
        addIcon("Maracas", "Events & Places", "type_event_and_place_maracas", R.drawable.type_event_and_place_maracas)
        addIcon("Milky way", "Events & Places", "type_event_and_place_milky_way", R.drawable.type_event_and_place_milky_way)
        addIcon("Moon Viewing", "Events & Places", "type_event_and_place_moon_viewing_ceremony", R.drawable.type_event_and_place_moon_viewing_ceremony)
        addIcon("Night Stars", "Events & Places", "type_event_and_place_night_with_stars", R.drawable.type_event_and_place_night_with_stars)
        addIcon("Mount Fuji", "Events & Places", "type_event_and_place_mount_fuji", R.drawable.type_event_and_place_mount_fuji)
        addIcon("Mountain", "Events & Places", "type_event_and_place_mountain", R.drawable.type_event_and_place_mountain)
        addIcon("National Park", "Events & Places", "type_event_and_place_national_park", R.drawable.type_event_and_place_national_park)
        addIcon("Post Office", "Events & Places", "type_event_and_place_post_office", R.drawable.type_event_and_place_post_office)
        addIcon("Snowman", "Events & Places", "type_event_and_place_snowman", R.drawable.type_event_and_place_snowman)
        addIcon("Snowman without snow", "Events & Places", "type_event_and_place_snowman_without_snow", R.drawable.type_event_and_place_snowman_without_snow)

        // Human
        addIcon("Baby", "Human", "type_human_baby", R.drawable.type_human_baby)
        addIcon("Parents", "Human", "type_human_parents", R.drawable.type_human_parents)
        addIcon("GrandParents", "Human", "type_human_grandparents", R.drawable.type_human_grandparents)
        addIcon("Woman", "Human", "type_human_woman", R.drawable.type_human_woman)
        addIcon("Woman Blonde", "Human", "type_human_woman_blonde", R.drawable.type_human_woman_blonde)
        addIcon("Old Woman", "Human", "type_human_old_woman", R.drawable.type_human_old_woman)
        addIcon("Man", "Human", "type_human_man", R.drawable.type_human_man)
        addIcon("Man Bald", "Human", "type_human_man_bald", R.drawable.type_human_man_bald)
        addIcon("Man Beard", "Human", "type_human_man_beard", R.drawable.type_human_man_beard)
        addIcon("Man Blonde", "Human", "type_human_man_blonde", R.drawable.type_human_man_blonde)
        addIcon("Man Curly Hair", "Human", "type_human_man_curly_hair", R.drawable.type_human_man_curly_hair)
        addIcon("Old Man", "Human", "type_human_old_man", R.drawable.type_human_old_man)
        addIcon("Older Person", "Human", "type_human_older_person", R.drawable.type_human_older_person)

        return icons
    }
}
